### ISSUE TITLE
Move tests from Mocha to AVA

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/cp-file#10]
https://github.com/sindresorhus/cp-file/blob/master/test.js
https://github.com/avajs/ava

Would be a good first issue. Anyone wanna give it a shot?

**Comment by schnittstabil** [comment]
@sindresorhus Is it ok for you, if we drop support for node v0.10? LTS ends tomorrow and I want to get rid of the `buffer-equals` ponyfill within the tests. Additionally, `pinkie-promise` won't be needed anymore…

**Comment by feross** [comment]
+1 to getting rid of the Promise polyfills! Fewer deps!

**Comment by sindresorhus** [comment]
👍

**Comment by feross** [comment]
PR sent to remove 3 unneeded deps: https://github.com/sindresorhus/cp-file/pull/11
