### ISSUE TITLE
Expose a non-event-emitter-returning variant which plays nice(r) with gulp v4?

### ISSUE THREAD

**Issue by chocolateboy** [sindresorhus/cp-file#17]
**cp-file**: 4.1.1
**gulp**: `gulpjs/gulp#4.0`
**async-done**: 1.2.2
**Node.js**: v7.4.0
**OS**: Linux (Arch)

As per gulpjs/async-done/issues/36, cp-file doesn't Just Work™ out of the box with gulp v4:

### gulpfile.js

```javascript
import copy from 'cp-file'
import gulp from 'gulp'

gulp.task('copy', () => copy('foo.txt', 'bar.txt'))
```
### output

```
$ gulp copy
Using gulpfile ~/temp/copy-file-test/gulpfile.js
Starting 'copy'...
The following tasks did not complete: copy
Did you forget to signal async completion?
```

Any chance it could export a variant which just returns a promise e.g.:

```javascript
const copy = require('cp-file').compat // noProgress?

gulp.task('copy', () => copy(src, dest))
```

rather than my current workaround:

```javascript
gulp.task('copy', done => {
    // .then(done): work around a gulp issue (in async-done) which interprets
    // copy's return value as a (non-terminating) event emitter rather than a promise
    // https://github.com/gulpjs/async-done/issues/36
    return copy(src, dest).then(done)
})
```

**Comment by sindresorhus** [comment]
Your original assessment was correct. This is a problem with the Gulp detection of a stream.

> An obvious solution would be to check if the return value is a promise before checking if it's an event emitter. Better still, why not use is-stream to check if it's actually a stream?

This is how it should have been done indeed.

---

The beauty of promises is that they can be [any object with a `.then()` method](https://github.com/then/is-promise/blob/ff47ce59dcc631ca8decdde5d7aa186c9c9681b9/index.js#L4).

I realize this is inconvenient for you, but I'm done working around the badness of Gulp. I've done that for way too long. You could maybe try `gulp.task('copy', () => copy(src, dest).then(_ => _))` or `gulp.task('copy', () => Promise.resolve().then(() => copy(src, dest))`.

**Comment by schnittstabil** [comment]
Or:
```js
gulp.task('copy', () => Promise.resolve(copy(src, dest))).
```

**Comment by schnittstabil** [comment]
> I'm done working around the badness of Gulp.

Sometimes, it's not the badness of a library, it's the badness how issues are handled :unamused:

Sorry @chocolateboy, `cp-file` clearly returns a Promise and not an EventEmitter (and therefore not a Stream either):
```js
cpFile('index.js', 'index.js.bkp') instanceof Promise
// => true

cpFile('index.js', 'index.js.bkp') instanceof EventEmitter
// => false
```

We just add an [`on` method at line 52](https://github.com/sindresorhus/cp-file/blob/36349c8eca44d1a90ab332d64f1d4c3034ef14a8/index.js#L52) which confuses `async-done`, that's all:
```js
promise.on = function () {…};
```

@chocolateboy Unfortunately, @phated seems neither being interested in `async-done` improvements nor in understanding the problem, hence I believe you are out of luck.

**Comment by schnittstabil** [comment]
Btw, adding an `on` method fully complies with the [ECMAScript® 2015 Language Specification](http://www.ecma-international.org/ecma-262/6.0/#sec-promise-constructor):

> The `Promise` constructor is designed to be subclassable. It may be used as the value in an `extends` clause of a class definition. […]
