### ISSUE TITLE
Use the `COPYFILE_FICLONE` constant

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/cp-file#27]
For faster copy.

https://nodejs.org/api/fs.html#fs_fs_copyfile_src_dest_flags_callback

**Comment by wmertens** [comment]
Just wondering how this would be implemented:
* check if `COPYFILE_FICLONE` flag exists
* if so, call `fs.copyFile` and emit progress 0, then progress 100% on completion

For the sync version, just add the flag if it exists

Right?

**Comment by sindresorhus** [comment]
Let's wait a little bit with this. It has some issues: https://github.com/nodejs/node/issues/27273

**Comment by wmertens** [comment]
Since the problem will always exist with the current mode versions, how about working around it keyed by version and platform?

**Comment by sindresorhus** [comment]
> Since the problem will always exist with the current Node versions

Current patch versions, you're right, but the Node.js team backports fixes all the time, so might be fixed in a patch/minor Node.js 8 version. I prefer to hold on for a bit and see if they'll do.

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the initial attempt and feedback in https://github.com/sindresorhus/cp-file/pull/40.
