### ISSUE TITLE
need feedback if copy fails because overwrite: false

### ISSUE THREAD

**Issue by boneskull** [sindresorhus/cp-file#37]
When using `overwrite: false`, there's no feedback (apart from a progress bar, perhaps, but that's not relevant to my use case) as to whether or not the copy succeeded. this error is _explicitly_ eaten, so I realize rejecting here is _not_ the desired behavior.

But I'm wondering if it's possible to provide _some_ sort of feedback in this case?  Either resolve with a value, or add another option to enable reject-on-existing-file...

Please let me know what you think; I can probably send a PR.

**Comment by sindresorhus** [comment]
If `overwrite: false` doesn't reject when the file exists, it's definitely a bug. It should do that.
