### ISSUE TITLE
Please fix make-dir security issue.

### ISSUE THREAD

**Issue by makeupyourmind** [sindresorhus/cp-file#53]
The npm audit report says the `cp-file` package has a vulnerability:

![image](https://github.com/sindresorhus/cp-file/assets/46902917/939a2995-635f-4d50-8301-365fa526cde8)

Here is a security issue - https://security.snyk.io/package/npm/semver/6.3.0.

Please bump the `make-dir` package version.

Thanks in advance.

**Comment by sindresorhus** [comment]
There is no `make-dir` dependency in the latest `cp-file` version.

**Comment by makeupyourmind** [comment]
> There is no `make-dir` dependency in the latest `cp-file` version.

However it looks like you need to bump the `cpy` version in the `cpy-cli` package.
Here is corresponding issue: https://github.com/sindresorhus/cpy-cli/issues/44.
Thanks.
